/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.student_manage.views;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.student.idgenarator.IDGenarator;
import lk.ijse.student_manage.controller.ControllerFactory;
import lk.ijse.student_manage.controller.custom.BatchTranferController;
import lk.ijse.student_manage.controller.custom.impl.BatchTransferControllerImpl;
import lk.ijse.student_manage.dto.BatchTranferDTO;

/**
 *
 * @author chamara
 */           
public class BatchTransfer extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    
    BatchTranferController batchTranferController = new BatchTransferControllerImpl();
    
    public BatchTransfer() {
        initComponents();
         BTI.setBorder(null);
        NewBatch.setBorder(null);
        txtAddBatch.setBorder(null);
        txtxsid.setBorder(null);
        txtRId.setBorder(null);
        txtfee.setBorder(null);
        txtdate.setBorder(null);
      //  IDGenarator();
     //   txtbatcStatus.setBorder(null);
      batchTranferController = (BatchTranferController)ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.BatchTransfer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btAddStudent = new javax.swing.JLabel();
        btUpdateStudent = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BTI = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtxsid = new javax.swing.JTextField();
        txtAddBatch = new javax.swing.JTextField();
        txtRId = new javax.swing.JTextField();
        txtfee = new javax.swing.JTextField();
        txtdate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NewBatch = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        txtwrite = new javax.swing.JTextField();
        typecombo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("BTI");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 117, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 200, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 62, 200, 0));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 200, -1));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 200, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Sid");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 140, 30));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 200, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 172, 200, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 110, 200, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("TrasnFerDate");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, 99, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "TID", "RID", "SID", "BIDOld", "BIDNew", "TrasnferDate", "TransFerfee"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 1249, 300));

        btAddStudent.setBackground(new java.awt.Color(51, 204, 255));
        btAddStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btAddStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btAddStudent.setText("Add BatchTransfer");
        btAddStudent.setOpaque(true);
        btAddStudent.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btAddStudentAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btAddStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAddStudentMouseClicked(evt);
            }
        });
        jPanel1.add(btAddStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 180, 30));

        btUpdateStudent.setBackground(new java.awt.Color(0, 204, 102));
        btUpdateStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btUpdateStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btUpdateStudent.setText("Update Student");
        btUpdateStudent.setOpaque(true);
        btUpdateStudent.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btUpdateStudentAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btUpdateStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btUpdateStudentMouseClicked(evt);
            }
        });
        jPanel1.add(btUpdateStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 200, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Rid");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 151, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Add Batch");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 140, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("TransFerfee");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, 130, 30));

        BTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTIActionPerformed(evt);
            }
        });
        jPanel1.add(BTI, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 202, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 200, -1));

        txtxsid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtxsidActionPerformed(evt);
            }
        });
        jPanel1.add(txtxsid, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 184, 202, -1));

        txtAddBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddBatchActionPerformed(evt);
            }
        });
        jPanel1.add(txtAddBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 202, -1));

        txtRId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtRId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 202, -1));

        txtfee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfeeActionPerformed(evt);
            }
        });
        jPanel1.add(txtfee, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 40, 202, -1));
        jPanel1.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 90, 202, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("New batch");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 117, 30));

        NewBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBatchActionPerformed(evt);
            }
        });
        jPanel1.add(NewBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 202, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 200, -1));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 60, 200, -1));

        txtwrite.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtwrite.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtwrite.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        txtwrite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtwriteActionPerformed(evt);
            }
        });
        txtwrite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtwriteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtwriteKeyReleased(evt);
            }
        });
        jPanel1.add(txtwrite, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 320, 200, 30));

        typecombo.setBackground(new java.awt.Color(0, 255, 255));
        typecombo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        typecombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SID", "Name", "Address", "Telephone", "School", "email", "dob" }));
        typecombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typecomboItemStateChanged(evt);
            }
        });
        typecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typecomboActionPerformed(evt);
            }
        });
        jPanel1.add(typecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 170, 31));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAddStudentMouseClicked
      
    }//GEN-LAST:event_btAddStudentMouseClicked

    private void btUpdateStudentAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btUpdateStudentAncestorAdded
 /* BatchTranferDTO batchTranfe = new BatchTranferDTO(
            BTI.getText(),
            NewBatch.getText(),
           txtAddBatch.getText(),
            txtxsid.getText(),
           txtRId.getText(),
            txtfee.getText(),
            txtdate.getText());
            //txtbatcStatus.getText());
          
        try {
            boolean result = batchTranferController.update(batchTranfe);
          
              if (result) {
                JOptionPane.showMessageDialog(this, "BatchTranfer has been successfully added...!");
            } else {
                JOptionPane.showMessageDialog(this, "BatchTranfer has not been added...!");
            }
       } catch (Exception ex) {
            Logger.getLogger(Course.class.getName()).log(Level.SEVERE, null, ex);
        
        }
        

       // private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {
   */
    }//GEN-LAST:event_btUpdateStudentAncestorAdded

    private void btUpdateStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btUpdateStudentMouseClicked

        
    }//GEN-LAST:event_btUpdateStudentMouseClicked

    private void BTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTIActionPerformed

    private void NewBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewBatchActionPerformed

    private void txtRIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRIdActionPerformed

    private void txtAddBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddBatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddBatchActionPerformed

    private void txtxsidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtxsidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtxsidActionPerformed

    private void txtfeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfeeActionPerformed

    private void txtwriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtwriteActionPerformed
    //    addTableDetails();
    }//GEN-LAST:event_txtwriteActionPerformed

    private void txtwriteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtwriteKeyPressed

    }//GEN-LAST:event_txtwriteKeyPressed

    private void txtwriteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtwriteKeyReleased
       // this.searchType = (String) typecombo.getSelectedItem();
        //searchStudentDetails(searchType, txtwrite.getText());
    }//GEN-LAST:event_txtwriteKeyReleased

    private void typecomboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typecomboItemStateChanged
       // txtwrite.setText("");
       // this.searchType = (String) typecombo.getSelectedItem();
    }//GEN-LAST:event_typecomboItemStateChanged

    private void typecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typecomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typecomboActionPerformed

    private void btAddStudentAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btAddStudentAncestorAdded
         try {
        BatchTranferDTO batchTranfe = new BatchTranferDTO(
            BTI.getText(),
            NewBatch.getText(),
           txtAddBatch.getText(),
            txtxsid.getText(),
           txtRId.getText(),
            txtfee.getText(),
            txtdate.getText());
            //txtbatcStatus.getText());
          
        
            boolean result = batchTranferController.add(batchTranfe);
          
              if (result) {
                JOptionPane.showMessageDialog(this, "BatchTranfer has been successfully added...!");
            } else {
                JOptionPane.showMessageDialog(this, "BatchTranfer has not been added...!");
            }
       } catch (Exception ex) {
         
            Logger.getLogger(BatchTransfer.class.getName()).log(Level.SEVERE, null, ex);
        
        }
        
                                            

    }//GEN-LAST:event_btAddStudentAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BatchTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BatchTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BatchTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BatchTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BatchTransfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BTI;
    private javax.swing.JTextField NewBatch;
    private javax.swing.JLabel btAddStudent;
    private javax.swing.JLabel btUpdateStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAddBatch;
    private javax.swing.JTextField txtRId;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtfee;
    private javax.swing.JTextField txtwrite;
    private javax.swing.JTextField txtxsid;
    private javax.swing.JComboBox typecombo;
    // End of variables declaration//GEN-END:variables
  private void IDGenarator() {

        try {
            BTI.setText(IDGenarator.getNewID("batchtranfer", " BTI", "BT"));

        } catch (SQLException ex) {
            Logger.getLogger(Course.class
                    .getName()).log(Level.SEVERE, null, ex);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Course.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
