/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.student_manage.views;

import java.awt.DefaultKeyboardFocusManager;
import java.awt.KeyEventPostProcessor;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import static java.lang.System.exit;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author chamara
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
          setDate();
        setTime();
        ShortKeys();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Homepnel = new javax.swing.JPanel();
        lblclose2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblclose1 = new javax.swing.JLabel();
        HOME_TIME = new javax.swing.JTextField();
        lblclose = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        HOME_TIME1 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Homepnel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblclose2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblclose2MouseClicked(evt);
            }
        });
        Homepnel.add(lblclose2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Registration");
        Homepnel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, 150, 40));

        lblclose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblclose1MouseClicked(evt);
            }
        });
        Homepnel.add(lblclose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        HOME_TIME.setBackground(new java.awt.Color(0, 51, 51));
        HOME_TIME.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        HOME_TIME.setForeground(new java.awt.Color(255, 255, 255));
        Homepnel.add(HOME_TIME, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 180, 30));

        lblclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcloseMouseClicked(evt);
            }
        });
        Homepnel.add(lblclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("data backup");
        Homepnel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 410, 160, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("log out");
        Homepnel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 620, 120, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("payment");
        Homepnel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 630, 130, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Course");
        jLabel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Homepnel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 234, 170, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("settings");
        Homepnel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 110, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Student");
        Homepnel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 110, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Batch");
        Homepnel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, 130, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("batch transfer");
        Homepnel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 630, 180, 30));

        HOME_TIME1.setBackground(new java.awt.Color(0, 51, 51));
        HOME_TIME1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        HOME_TIME1.setForeground(new java.awt.Color(255, 255, 255));
        Homepnel.add(HOME_TIME1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 10, 180, 30));

        jButton12.setBackground(new java.awt.Color(51, 204, 255));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/student/icon/images (1)_1.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        Homepnel.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 210, 180));

        jButton11.setBackground(new java.awt.Color(51, 204, 255));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/student/icon/500_F_113168763_JS3opQgPD3TMNx8ullZVtRPlga47HFfQ.jpg"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        Homepnel.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 430, 180));

        jButton10.setBackground(new java.awt.Color(102, 204, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/student/icon/012_power-512_1.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        Homepnel.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, 430, 180));

        jButton9.setBackground(new java.awt.Color(51, 204, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/student/icon/Settings-icon.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        Homepnel.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 410, 170));

        jButton8.setBackground(new java.awt.Color(51, 204, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/student/icon/download_2.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        Homepnel.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 280, 210, 170));

        jButton7.setBackground(new java.awt.Color(51, 204, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/student/icon/download (3).jpg"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        Homepnel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 210, 170));

        jButton6.setBackground(new java.awt.Color(51, 204, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/student/icon/icons8-student-male-48.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        Homepnel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 210, 180));

        jButton5.setBackground(new java.awt.Color(0, 204, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/student/icon/images (1).png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Homepnel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 190, 180));

        jButton4.setBackground(new java.awt.Color(51, 204, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/student/icon/money-colored-15-512.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Homepnel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 190, 180));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/student/icon/3d-wallpaper-wallpapers-for-free-download-about-3-390-5af40dc549e67_2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        Homepnel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1360, 810));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        Homepnel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 470, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Homepnel, javax.swing.GroupLayout.PREFERRED_SIZE, 1617, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Homepnel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        BackupForm backupForm = new BackupForm();
        backupForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       BatchTransfer batchTransfer = new BatchTransfer();
       batchTransfer.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
       Course coures = new Course();
        coures.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void lblcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcloseMouseClicked
       // exit s = new exit(this, true);
     //   s.setVisible(true);
        /*int ress=JOptionPane.showConfirmDialog(null,"Do You Wont To Exit..?","Exit",JOptionPane.YES_NO_OPTION);
        if(ress==YES_OPTION){
            System.exit(0);*/

    }//GEN-LAST:event_lblcloseMouseClicked

    private void lblclose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblclose1MouseClicked
       // exit s = new exit(this, true);
        //s.setVisible(true);
        /*int ress=JOptionPane.showConfirmDialog(null,"Do You Wont To Exit..?","Exit",JOptionPane.YES_NO_OPTION);
        if(ress==YES_OPTION){
            System.exit(0);*/

    }//GEN-LAST:event_lblclose1MouseClicked

    private void lblclose2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblclose2MouseClicked
      //  exit s = new exit(this, true);
        //s.setVisible(true);
        /*int ress=JOptionPane.showConfirmDialog(null,"Do You Wont To Exit..?","Exit",JOptionPane.YES_NO_OPTION);
        if(ress==YES_OPTION){
            System.exit(0);*/

    }//GEN-LAST:event_lblclose2MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
studentview studentview=new studentview();
studentview.setVisible(true);
this.dispose();
//        lblclose2.setVisible(true);
//        
//       studentview mf=new studentview();
//       mf.setSize(Homepnel.getSize());
//       Homepnel.removeAll();
//       Homepnel.add(mf);
//       Homepnel.repaint();
//       Homepnel.revalidate();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
      Registration registration=new Registration();
     registration.setVisible(true);
              this.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        batch batch1= new batch();
        batch1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       peyment  payment1= new peyment();
       payment1.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       login ml=new login();
        ml.setVisible(true);
        Home m1=new Home();
        dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jLabel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel2AncestorAdded
        
    }//GEN-LAST:event_jLabel2AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HOME_TIME;
    private javax.swing.JTextField HOME_TIME1;
    private javax.swing.JPanel Homepnel;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblclose;
    private javax.swing.JLabel lblclose1;
    private javax.swing.JLabel lblclose2;
    // End of variables declaration//GEN-END:variables
  private void setTime() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    Date date = new Date();
                    String currentdate = new SimpleDateFormat("hh:mm:aa").format(date);
                    HOME_TIME.setText(currentdate);

                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {

                    }
                }
            }
        }).start();
    }

    private void setDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        HOME_TIME1.setText(s.format(d));

    }

          private void ShortKeys() {
              KeyboardFocusManager k = DefaultKeyboardFocusManager.getCurrentKeyboardFocusManager();
        k.addKeyEventPostProcessor(new KeyEventPostProcessor() {
            @Override
            public boolean postProcessKeyEvent(KeyEvent e) {
                System.out.println(e.getKeyCode());
                switch (e.getKeyCode()) {

                    case KeyEvent.VK_F1:
                        if (e.getID() == KeyEvent.KEY_PRESSED) {
                            Registration registration = new Registration();
                            registration.setVisible(true);
                            dispose();
                        }
                        break;
                    case KeyEvent.VK_F2:
                        if (e.getID() == KeyEvent.KEY_PRESSED) {
                            peyment payments = new peyment();
                            payments.setVisible(true);
                            dispose();
                        }
                        break;
                    case KeyEvent.VK_F3:
                        if (e.getID() == KeyEvent.KEY_PRESSED) {
                            batch manageCourse = new batch();
                            manageCourse.setVisible(true);
                            dispose();
                        }
                        break;
                    case KeyEvent.VK_F4:
                        if (e.getID() == KeyEvent.KEY_PRESSED) {
                            studentview manageBatch = new studentview();
                            manageBatch.setVisible(true);
                            dispose();
                        }
                        break;
                    case KeyEvent.VK_F5:
                        if (e.getID() == KeyEvent.KEY_PRESSED) {
                            Course checkPaymentStates = new Course();
                            checkPaymentStates.setVisible(true);
                            dispose();
                        }
                        break;
                    case KeyEvent.VK_F6:
                        if (e.getID() == KeyEvent.KEY_PRESSED) {
                            studentview studentDetails = new studentview();
                            studentDetails.setVisible(true);
                            dispose();
                        }
                        break;
                    case KeyEvent.VK_F7:
                        if (e.getID() == KeyEvent.KEY_PRESSED) {
                            BatchTransfer batchTransfer = new BatchTransfer();
                            batchTransfer.setVisible(true);
                            dispose();
                        }
                        break;
                }
                return true;
            }
        });
        this.dispose();
    }




}
