/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.student_manage.views;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.View;
import lk.ijse.student.idgenarator.IDGenarator;
import lk.ijse.student_manage.controller.ControllerFactory;
import lk.ijse.student_manage.controller.custom.StudentController;
import lk.ijse.student_manage.controller.custom.impl.StudentControllerImpl;
import lk.ijse.student_manage.dto.StudentDTO;

/**
 *
 * @author chamara
 *
 */
public class studentview extends javax.swing.JFrame {

    private ArrayList<StudentDTO> StudentList;

    private String searchType = "";
    private ArrayList<StudentDTO> searchStudentList;

    /**
     * Creates new form studentview
     */
    StudentController studentcotroller = new StudentControllerImpl();

    
      private void clearTextFields() {
        tfSID.setText("");
        tfName.setText("");
        TxtDateOfBirth.setText("");
         txtemail1.setText("");
         txtSchool.setText("");
         txtAddress.setText("");
         txtNice.setText("");
         txtwrite.setText("");
    }

    
    
    
    public studentview() {
        initComponents();
        getAllStudentDetails();
        IDGenarator();
        
        
        tfSID.setBorder(null);
        tfName.setBorder(null);
        TxtDateOfBirth.setBorder(null);
        txtemail1.setBorder(null);
        txtSchool.setBorder(null);
        txtAddress.setBorder(null);
        txtNice.setBorder(null);
        txtwrite.setBorder(null);
        TxtTel.setBorder(null);

        studentcotroller = (StudentController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.STUDENT);

        StudentTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {

                if (StudentTable.getSelectedRow() == -1) {
                    return;
                }

                tfSID.setText(StudentTable.getValueAt(StudentTable.getSelectedRow(), 0).toString());
               // tfNIC.setText(StudentTable.getValueAt(StudentTable.getSelectedRow(), 1).toString());
                tfName.setText(StudentTable.getValueAt(StudentTable.getSelectedRow(), 1).toString());
                txtAddress.setText(StudentTable.getValueAt(StudentTable.getSelectedRow(), 2).toString());
                TxtDateOfBirth.setText(StudentTable.getValueAt(StudentTable.getSelectedRow(), 3).toString());
                txtNice.setText(StudentTable.getValueAt(StudentTable.getSelectedRow(), 4).toString());
                txtemail1.setText(StudentTable.getValueAt(StudentTable.getSelectedRow(), 5).toString());
                txtSchool.setText(StudentTable.getValueAt(StudentTable.getSelectedRow(), 6).toString());
                TxtTel.setText(StudentTable.getValueAt(StudentTable.getSelectedRow(), 8).toString());
                comboGender.setSelectedItem(StudentTable.getValueAt(StudentTable.getSelectedRow(),7).toString());

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkerboardPainter1 = new org.jdesktop.swingx.painter.CheckerboardPainter();
        checkerboardPainter2 = new org.jdesktop.swingx.painter.CheckerboardPainter();
        email2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        txtNice = new javax.swing.JTextField();
        typecombo = new javax.swing.JComboBox();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        StudentTable = new org.jdesktop.swingx.JXTable();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        txtwrite = new javax.swing.JTextField();
        TxtTel = new javax.swing.JTextField();
        txtSchool = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtemail1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        txtAddress = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        btAddStudent = new javax.swing.JLabel();
        btUpdateStudent = new javax.swing.JLabel();
        comboGender = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        tfSID = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        TxtDateOfBirth = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtel = new org.jdesktop.swingx.JXLabel();
        jXMultiSplitPane1 = new org.jdesktop.swingx.JXMultiSplitPane();
        jXCollapsiblePane1 = new org.jdesktop.swingx.JXCollapsiblePane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        email3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        tfTel1 = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Next");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 680, 90, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 102, 230, -1));

        txtNice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNiceActionPerformed(evt);
            }
        });
        getContentPane().add(txtNice, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 230, -1));

        typecombo.setBackground(new java.awt.Color(0, 255, 255));
        typecombo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        typecombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SID", "Name", "Address", "Telephone", "School", "email", "dob" }));
        typecombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typecomboItemStateChanged(evt);
            }
        });
        typecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typecomboActionPerformed(evt);
            }
        });
        getContentPane().add(typecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 170, 31));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 230, -1));

        StudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "FUll Name", "Address", "Email", "dob", "Telephone", "School", "gender", "NIc"
            }
        ));
        jScrollPane3.setViewportView(StudentTable);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 1300, 220));
        getContentPane().add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 230, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 102, 230, -1));
        getContentPane().add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 380, 200, -1));

        txtwrite.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtwrite.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtwrite.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        txtwrite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtwriteActionPerformed(evt);
            }
        });
        txtwrite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtwriteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtwriteKeyReleased(evt);
            }
        });
        getContentPane().add(txtwrite, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 350, 200, 30));
        getContentPane().add(TxtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 240, -1));
        getContentPane().add(txtSchool, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 230, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("gender");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 60, 20));

        txtemail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemail1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtemail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 230, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("School/univercity");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 140, -1));
        getContentPane().add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 230, -1));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 230, -1));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 230, -1));
        getContentPane().add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 74, 230, -1));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 134, 230, 0));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 230, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 230, -1));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 132, 230, 0));
        getContentPane().add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 230, -1));

        btAddStudent.setBackground(new java.awt.Color(51, 204, 255));
        btAddStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btAddStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btAddStudent.setText("Add Student");
        btAddStudent.setOpaque(true);
        btAddStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAddStudentMouseClicked(evt);
            }
        });
        getContentPane().add(btAddStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 140, 30));

        btUpdateStudent.setBackground(new java.awt.Color(0, 204, 102));
        btUpdateStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btUpdateStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btUpdateStudent.setText("Update Student");
        btUpdateStudent.setOpaque(true);
        btUpdateStudent.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btUpdateStudentAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btUpdateStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btUpdateStudentMouseClicked(evt);
            }
        });
        getContentPane().add(btUpdateStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 150, 30));

        comboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male", "female" }));
        getContentPane().add(comboGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 230, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 350, 110, -1));

        btn_refresh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        getContentPane().add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 370, 20, 10));

        tfSID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSIDActionPerformed(evt);
            }
        });
        getContentPane().add(tfSID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 230, -1));
        getContentPane().add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 230, -1));

        TxtDateOfBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDateOfBirthActionPerformed(evt);
            }
        });
        getContentPane().add(TxtDateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 230, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Nic");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 50, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Email");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 50, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Student ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 80, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Full Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Date of Birth");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 130, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Tel");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 20, -1));

        txtel.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 10, 1460, 740));
        getContentPane().add(jXMultiSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, -1, -1));
        getContentPane().add(jXCollapsiblePane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/student/icon/download (1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 780, 540));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 210, 240));
        getContentPane().add(email3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 230, -1));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 52, 230, 10));

        tfTel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTel1ActionPerformed(evt);
            }
        });
        getContentPane().add(tfTel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, 230, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAddStudentMouseClicked
        try {
            //System.out.println("ghjkl");
            StudentDTO student = new StudentDTO(
                    tfSID.getText(),
                    tfName.getText(),
                    txtAddress.getText(),
                    txtemail1.getText(),
                    TxtDateOfBirth.getText(),
                    TxtTel.getText(),
                    txtSchool.getText(),
                    txtNice.getText(),
                    (String) comboGender.getSelectedItem());
            
            boolean result = studentcotroller.add(student);
            getAllStudentDetails();
            if (result) {
                JOptionPane.showMessageDialog(this, "Student has been successfully added...!");
            } else {
                JOptionPane.showMessageDialog(this, "Student has not been added...!");
            }
        } catch (Exception ex) {
            Logger.getLogger(studentview.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btAddStudentMouseClicked

    private void btUpdateStudentAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btUpdateStudentAncestorAdded

    }

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {


    }//GEN-LAST:event_btUpdateStudentAncestorAdded

    private void btUpdateStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btUpdateStudentMouseClicked

        StudentDTO student = new StudentDTO(
                 tfSID.getText(),
                tfName.getText(),
                txtAddress.getText(),
                txtemail1.getText(),
                TxtDateOfBirth.getText(),
                txtel.getText(),
                txtSchool.getText(), 
                txtNice.getText(),
                (String) comboGender.getSelectedItem());

        try {
            // System.out.println("Clickd");
            boolean result = studentcotroller.update(student);
            getAllStudentDetails();
            //  System.out.println(result);

            if (result) {
                JOptionPane.showMessageDialog(this, "Customer has been successfully updated...!");
            } else {
                JOptionPane.showMessageDialog(this, "Customer has not been updated...!");
            }
        } catch (Exception ex) {
           
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btUpdateStudentMouseClicked

    private void tfSIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSIDActionPerformed

    private void txtemail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemail1ActionPerformed

    private void TxtDateOfBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDateOfBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDateOfBirthActionPerformed

    private void typecomboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typecomboItemStateChanged
        txtwrite.setText("");
        this.searchType = (String) typecombo.getSelectedItem();
    }//GEN-LAST:event_typecomboItemStateChanged

    private void typecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typecomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typecomboActionPerformed

    private void txtwriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtwriteActionPerformed
        addTableDetails();
    }//GEN-LAST:event_txtwriteActionPerformed

    private void txtwriteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtwriteKeyPressed

    }//GEN-LAST:event_txtwriteKeyPressed

    private void txtwriteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtwriteKeyReleased
        this.searchType = (String) typecombo.getSelectedItem();
        searchStudentDetails(searchType, txtwrite.getText());

    }//GEN-LAST:event_txtwriteKeyReleased

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       Registration registrationView = new Registration();
        registrationView.setVisible(true);
                StudentDTO student = new StudentDTO(
                 tfSID.getText(),
                tfName.getText(),
                txtAddress.getText(),
                txtemail1.getText(),
                TxtDateOfBirth.getText(),
                TxtTel.getText(),
                txtSchool.getText(), 
                txtNice.getText(),
                (String) comboGender.getSelectedItem());
                
                registrationView.getStudentDetails(student);
        removeAll();
    }//GEN-LAST:event_jButton1MouseClicked

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        getAllStudentDetails();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        clearTextFields() ;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtNiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNiceActionPerformed

    private void tfTel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXTable StudentTable;
    private javax.swing.JTextField TxtDateOfBirth;
    private javax.swing.JTextField TxtTel;
    private javax.swing.JLabel btAddStudent;
    private javax.swing.JLabel btUpdateStudent;
    private javax.swing.JButton btn_refresh;
    private org.jdesktop.swingx.painter.CheckerboardPainter checkerboardPainter1;
    private org.jdesktop.swingx.painter.CheckerboardPainter checkerboardPainter2;
    private javax.swing.JComboBox<String> comboGender;
    private javax.swing.JTextField email2;
    private javax.swing.JTextField email3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private org.jdesktop.swingx.JXCollapsiblePane jXCollapsiblePane1;
    private org.jdesktop.swingx.JXMultiSplitPane jXMultiSplitPane1;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfSID;
    private javax.swing.JTextField tfTel1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtNice;
    private javax.swing.JTextField txtSchool;
    private org.jdesktop.swingx.JXLabel txtel;
    private javax.swing.JTextField txtemail1;
    private javax.swing.JTextField txtwrite;
    private javax.swing.JComboBox typecombo;
    // End of variables declaration//GEN-END:variables
 private void addTableDetails() {
    }

    private void getAllStudentDetails() {
        try {
            this.StudentList = (ArrayList<StudentDTO>) studentcotroller.getAll();

            DefaultTableModel dtm = (DefaultTableModel) StudentTable.getModel();

            dtm.setRowCount(0);

            for (StudentDTO student : StudentList) {

                Object[] rowData = {student.getSID(),
                    student.getName(),
                    student.getAddress(),
                    student.getTelephone(),
                    student.getSchool(),
                    student.getGender(),
                    student.getEmail(),
                     student.getNic(),
                    student.getDob(),};
                    

                dtm.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void searchStudentDetails(String type, String searchText) {

        System.out.println("T"+searchType);
         System.out.println("st"+searchText);
        System.out.println("sL"+StudentList);
        System.out.println("Result  " + type.equals("SID"));
        if (type.equals("SID")) {

            searchStudentList = new ArrayList<>();
            for (StudentDTO studentDTO : StudentList) {
                if (studentDTO.getSID().toLowerCase().contains(searchText.toLowerCase())) {
                    searchStudentList.add(studentDTO);

                }
            }
        } else if (type.equals("Name")) {
            searchStudentList = new ArrayList<>();
            for (StudentDTO studentDTO : StudentList) {
                if (studentDTO.getName().toLowerCase().contains(searchText.toLowerCase())) {
                    searchStudentList.add(studentDTO);
                }
            }
        } else if (type.equals("Address")) {
            searchStudentList = new ArrayList<>();
            for (StudentDTO studentDTO : StudentList) {
                if (studentDTO.getAddress().toLowerCase().contains(searchText.toLowerCase())) {
                    searchStudentList.add(studentDTO);
                }
            }
        } else if (type.equals("Telephone")) {
            searchStudentList = new ArrayList<>();
            for (StudentDTO studentDTO : StudentList) {
                if (studentDTO.getTelephone().toLowerCase().contains(searchText.toLowerCase())) {
                    searchStudentList.add(studentDTO);
                }
            }
        } else if (type.equals("School")) {
            searchStudentList = new ArrayList<>();
            for (StudentDTO studentDTO : StudentList) {
                if (studentDTO.getSchool().toLowerCase().contains(searchText.toLowerCase())) {
                    searchStudentList.add(studentDTO);
                }

            }
        } else if (type.equals("email")) {
            searchStudentList = new ArrayList<>();
            for (StudentDTO studentDTO : StudentList) {
                if (studentDTO.getEmail().toLowerCase().contains(searchText.toLowerCase())) {
                    searchStudentList.add(studentDTO);

                }
            }
        } else if (type.equals("dob")) {
            searchStudentList = new ArrayList<>();
            for (StudentDTO studentDTO : StudentList) {
                if (studentDTO.getDob().toLowerCase().contains(searchText.toLowerCase())) {
                    searchStudentList.add(studentDTO);
                }
            }
        }
        try {

            DefaultTableModel dtm = (DefaultTableModel) StudentTable.getModel();

            dtm.setRowCount(0);

            for (StudentDTO student : searchStudentList) {

                Object[] rowData = {student.getSID(),
                    student.getName(),
                    student.getAddress(),
                    student.getTelephone(),
                    student.getSchool(),
                    student.getGender(),
                    student.getEmail(),
                    student.getDob(),};
                System.out.println("sL" + rowData);
                dtm.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    private void IDGenarator() {

        try {
            tfSID.setText(IDGenarator.getNewID("Student", " SID", "S"));

        } catch (SQLException ex) {
            Logger.getLogger(studentview.class
                    .getName()).log(Level.SEVERE, null, ex);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(studentview.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
